#! /bin/bash
# Decred Testnet Suite
#
# @license LGPL
# @author Walker de Alencar <@walkeralencar>
# @author contributors <@contributos>
DCR_VERSION="0.0.7"
DCR_FILE="linux-amd64-20160309-01.tar.gz"
DCR_URL="https://github.com/decred/decred-release/releases/download/v0.0.7/linux-amd64-20160309-01.tar.gz"
VERSION="0.2"
TITLE="DCRTS v$VERSION by Walker de Alencar - DCR Wallet: v$DCR_VERSION"

PWS=

commands (){
  header
  case "$1" in
    cleanup)
      cleanup
      ;;
    install)
      installer
      ;;
    uninstall)
      ;;
    help)
      howto
      ;;
    *)
      howto
      exit 1
  esac
  exit 0
}

header(){
  clear
  echo "Decred Testnet Suite v$VERSION"
  echo "Author: Walker de Alencar"
  echo "Wallet: v$DCR_VERSION"
  echo ""
}

howto(){
  echo "use: dcrtestnet {help|cleanup|install}"
  echo "  help     show this"
  echo "  cleanup  remove all files from testnet"
  echo "  install  creates symlinks on /usr/local/bin to use commands anywhere"
  echo ""
}

rootpass(){
  PWS=$(dialog --clear --stdout --backtitle "$TITLE" --title 'Installation' --passwordbox "\n[sudo] password for $USER: " 10 50)

  ret=$?

  case $ret in
    0)
      fixtty
      ;;
    *)
      dialog --clear --backtitle "$TITLE" --title "Installation" \
              --msgbox "\nInstallation was cancelled!" 7 31
      clear
      exit 1;
  esac
}

fixtty(){
  echo "$PWS" | sudo -S sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile
}

download(){
  wget -c "https://github.com/decred/decred-release/releases/download/v0.0.7/linux-amd64-20160309-01.tar.gz" 2>&1 | \
    stdbuf -o0 awk '/[.] +[0-9][0-9]?[0-9]?%/ { print substr($0,63,3) }' | \
    dialog --clear --backtitle "$TITLE" --title "Installation [1/4]" \
            --gauge "\n  Downloading file [$DCR_FILE] ..." 8 80
}

unpacking() {
  dialog --backtitle "$TITLE" --title "Installation [2/4]" \
          --infobox '\nUnpacking files...' 5 0
  tar -xvf "$DCR_FILE" > /dev/null
  mv linux-amd64/* ./   > /dev/null
  sleep 2
}


symlinks(){
  dialog  --backtitle "$TITLE" --title "Installation [3/4]" \
          --infobox '\nCreating symlinks...' 5 0
  sudo ln -sf `pwd`/dcrd /usr/local/bin/       > /dev/null
  sudo ln -sf `pwd`/dcrwallet /usr/local/bin/  > /dev/null
  sudo ln -sf `pwd`/dcrctl /usr/local/bin/     > /dev/null
  sudo ln -sf `pwd`/dcrstat /usr/local/bin/    > /dev/null
  sudo ln -sf `pwd`/dcrtestnet /usr/local/bin/ > /dev/null
  sleep 2
}

autoremove(){
  dialog --backtitle "$TITLE" --title "Installation [4/4]" \
          --infobox '\nAutoremove unused files...' 5 0
  rm -rf linux-amd*
  sleep 2
}

installer(){
  rootpass
  download
  unpacking
  symlinks
  autoremove
  dialog --clear --backtitle "$TITLE" --title "Installation" \
          --msgbox "\nInstallation complete!" 7 0
}

#Cleanup all testnet files
cleanup(){
  echo "Cleaning [Testnet] files"
  echo "Daemon[dcrd]:"
  echo -n "  Data... "
  rm -rf ~/.dcrd/data/testnet/ > /dev/null
  echo "OK"

  echo -n "  Logs... "
  rm -rf ~/.dcrd/logs/testnet/ > /dev/null
  echo "OK"

  echo -n "  Certs... "
  rm -rf ~/.dcrd/rpc.* > /dev/null
  echo "OK"

  echo "Wallet[drcwallet]:"
  echo -n "  Data... "
  rm -rf ~/.dcrwallet/testnet/ > /dev/null
  echo "OK"

  echo -n "  Logs... "
  rm -rf ~/.dcrwallet/logs/testnet > /dev/null
  echo "OK"

  echo -n "  Certs... "
  rm -rf ~/.dcrwallet/rpc.* > /dev/null
  echo "OK"
  echo "Complete Clean"
  echo ""
}

commands $1
