#!/bin/bash
# Decred Testnet Suite
#
# @license LGPL
# @author Walker de Alencar <@walkeralencar>
# @author contributors <@marioaugustorama>
DCR_VERSION="v0.1.0"
DCR_FILE="linux-amd64-20160418-01.tar.gz"
DCR_URL="https://github.com/decred/decred-release/releases/download/"${DCR_VERSION}"/"${DCR_FILE}
VERSION="v0.5"
TITLE="DCRTS ${VERSION} by Walker de Alencar - DCR Wallet: ${DCR_VERSION}"

PWS=

commands (){
  header
  case "$1" in
    cleanup)
      cleanup
      ;;
    install)
      installer
      ;;
    uninstall)
      ;;
    help)
      howto
      ;;
    *)
      howto
      exit 1
  esac
  exit 0
}

header(){
  clear
  echo "Decred Testnet Suite $VERSION"
  echo "Author: Walker de Alencar"
  echo "Wallet: $DCR_VERSION"
  echo ""
}

howto(){
  echo "use: dcrtestnet {help|cleanup|install}"
  echo "  help     show this"
  echo "  cleanup  remove all files from testnet"
  echo "  install  creates symlinks on /usr/local/bin to use commands anywhere"
  echo ""
}

checkdialog(){
if [ $(dpkg-query -W -f='${Status}' dialog 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
    echo "Dialog not found!"
    echo "Installing ..."
    sudo apt-get install dialog > /dev/null 2>&1
fi
}

rootpass(){

  PWS=$(dialog --clear --stdout --backtitle "$TITLE" --title 'Installation' --passwordbox "\n[sudo] password for $USER: " 10 50)

  ret=$?

  case $ret in
    0)
      fixtty
      ;;
    *)
      dialog --clear --backtitle "$TITLE" --title "Installation" \
              --msgbox "\nInstallation was cancelled!" 7 31
      clear
      exit 1;
  esac
}

fixtty(){
  echo "$PWS" | sudo -S sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile
}

download(){
  wget -c ${DCR_URL} 2>&1 | \
    stdbuf -o0 awk '/[.] +[0-9][0-9]?[0-9]?%/ { print substr($0,63,3) }' | \
    dialog --clear --backtitle "$TITLE" --title "Installation [1/4]" \
            --gauge "\n  Downloading file [$DCR_FILE] ..." 8 80
}

unpacking() {
  dialog --backtitle "$TITLE" --title "Installation [2/4]" \
          --infobox '\nUnpacking files...' 5 0
  tar -xvf "$DCR_FILE" > /dev/null
  mv linux-amd64/* ./   > /dev/null
  sleep 2
}

installing(){
  dialog  --backtitle "$TITLE" --title "Installation [3/4]" \
          --infobox '\nInstalling...' 5 0
  sudo mv `pwd`/dcrd /usr/local/bin/       > /dev/null
  sudo mv `pwd`/dcrwallet /usr/local/bin/  > /dev/null
  sudo mv `pwd`/dcrctl /usr/local/bin/     > /dev/null
  sudo ln -sf `pwd`/dcrts /usr/local/bin/ > /dev/null
  sleep 2
}

autoremove(){
  dialog --backtitle "$TITLE" --title "Installation [4/4]" \
          --infobox '\nAutoremove unused files...' 5 0
  rm -rf linux-amd* > /dev/null
  sleep 2
}

installer(){
  checkdialog
  if [[ $EUID -ne 0 ]]; then
    rootpass
  fi  
  download
  unpacking
  installing
  autoremove
  dialog --clear --backtitle "$TITLE" --title "Installation" \
          --msgbox "\nInstallation complete!" 7 0
}

#Cleanup all testnet files
cleanup(){
  echo "Cleaning [Testnet] files"
  echo "Daemon[dcrd]:"
  echo -n "  Data... "
  rm -rf ~/.dcrd/data/testnet/ > /dev/null
  echo "OK"

  echo -n "  Logs... "
  rm -rf ~/.dcrd/logs/testnet/ > /dev/null
  echo "OK"

  echo -n "  Certs... "
  rm -rf ~/.dcrd/rpc.* > /dev/null
  echo "OK"

  echo "Wallet[drcwallet]:"
  echo -n "  Data... "
  rm -rf ~/.dcrwallet/testnet/ > /dev/null
  echo "OK"

  echo -n "  Logs... "
  rm -rf ~/.dcrwallet/logs/testnet > /dev/null
  echo "OK"

  echo -n "  Certs... "
  rm -rf ~/.dcrwallet/rpc.* > /dev/null
  echo "OK"
  echo "Complete Clean"
  echo ""
}

commands $1
