#! /bin/bash
# Decred Testnet Suite
# https://github.com/decred/decred-release/releases/download/v0.0.7/linux-amd64-20160309-01.tar.gz
# @license LGPL
# @author Walker de Alencar <@walkeralencar>
# @author contributors <@contributos>
VERSION="0.1"
DCR_VERSION="0.0.7"

commands (){
  header
  case "$1" in
    cleanup)
      cleanup
      ;;
    help)
      howto
      ;;
    *)
      howto
      exit 1
  esac
 }

header(){
  clear
  echo "Decred Testnet Suite v$VERSION"
  echo "Author: Walker de Alencar"
  echo "Wallet: v$DCR_VERSION"
  echo ""
}

howto(){
  echo "use: dcrtestnet {help|cleanup}"
  echo "  help     show this"
  echo "  cleanup  remove all files from testnet"
  echo ""
}

#Cleanup all testnet files
cleanup(){
  echo "Cleaning [Testnet] files"
  echo "Daemon[dcrd]:"
  echo -n "  Data... "
  rm -rf ~/.dcrd/data/testnet/ > /dev/null
  echo "OK"

  echo -n "  Logs... "
  rm -rf ~/.dcrd/logs/testnet/ > /dev/null
  echo "OK"

  echo -n "  Certs... "
  rm -rf ~/.dcrd/rpc.* > /dev/null
  echo "OK"

  echo "Wallet[drcwallet]:"
  echo -n "  Data... "
  rm -rf ~/.dcrwallet/testnet/ > /dev/null
  echo "OK"

  echo -n "  Logs... "
  rm -rf ~/.dcrwallet/logs/testnet > /dev/null
  echo "OK"

  echo -n "  Certs... "
  rm -rf ~/.dcrwallet/rpc.* > /dev/null
  echo "OK"
  echo "Complete Clean"
  echo ""
}

commands $1
